openapi: 3.0.2
info:
  version: "1.0.0"
  title: "Wiki"
  description: "Simple wiki engine"
servers:
  - description: localhost
    url: http://localhost:8000/
paths:
  /:
    get:
      parameters:
        - $ref: "#/components/parameters/SortOrder"
      summary: View a list of wiki pages
      operationId: wiki.list
      responses:
        "200":
          $ref: "#/components/responses/HTML200"
    post:
      summary: Create new wiki page
      operationId: wiki.create
      requestBody:
        $ref: "#/components/requestBodies/Article"
      responses:
        "301":
          description: "Redirect to /edit/{title}"
  /view/{title}:
    parameters:
      - $ref: "#/components/parameters/Title"
      - $ref: "#/components/parameters/SortOrder"
    get:
      summary: View a wiki page
      operationId: wiki.view
      responses:
        "200":
          $ref: "#/components/responses/HTML200"
  /edit/{title}:
    parameters:
      - $ref: "#/components/parameters/Title"
      - $ref: "#/components/parameters/SortOrder"
    get:
      summary: Edit a wiki page
      operationId: wiki.edit
      responses:
        "200":
          $ref: "#/components/responses/HTML200"
    post:
      summary: Save a wiki page
      operationId: wiki.save
      requestBody:
        $ref: "#/components/requestBodies/Article"
      responses:
        "301":
          description: "Redirect to /view/{title}"
  /static:
    get:
      summary: Edit a wiki page
      operationId: static
      responses:
        "200":
          $ref: "#/components/responses/HTML200"
      x-wildcard: true
  /oas3-model:
    get:
      summary: Return the OAS3 model
      operationId: oas3.model
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OAS3"
            application/yaml:
              schema:
                $ref: "#/components/schemas/OAS3"
  /console:
    get:
      summary: OAS3 Web UI (Develper Console)
      operationId: oas3.console
      responses:
        "200":
          $ref: "#/components/responses/HTML200"
components:
  parameters:
    Title:
      in: path
      name: title
      required: true
      schema:
        $ref: "#/components/schemas/Title"
      description: A title of a wiki page
    SortOrder:
      in: cookie
      name: sort_order
      required: false
      schema:
        $ref: "#/components/schemas/SortOrder"
      description: Sorting order 1 or -1
  responses:
    HTML200:
      description: OK
      content:
        text/html:
          schema:
            $ref: "#/components/schemas/HTML"
  requestBodies:
    Article:
      description: Wiki Article
      requred: true
      content:
        application/x-www-form-urlencoded:
          schema:
            $ref: "#/components/schemas/Article"
  schemas:
    HTML:
      type: string
    OAS3:
      type: object
    Title:
      type: string
      minLength: 1
    SortOrder:
      type: integer
      minimum: -1
      maximum: 1
    Article:
      type: object
      properties:
        title:
          $ref: "#/components/schemas/Title"
        body:
          type: string
          minLength: 1
