name: Tests
on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
    branches:
      - master
      - v*
jobs:
  style:
    strategy:
      matrix:
        go-version: [1.13.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Run gofmt
        run: diff -u <(echo -n) <(gofmt -d -s .)
      - name: Run go vet
        run: go vet ./...
      - name: Install golint
        run: go get -u golang.org/x/lint/golint
      - name: Run golint
        run: ~/go/bin/golint -set_exit_status ./...
      - name: Install misspell
        run: go get -u github.com/client9/misspell/cmd/misspell
      - name: Run misspell
        run: ~/go/bin/misspell -error $(find . -name "*.go")
  unit-tests:
    strategy:
      matrix:
        go-version: [1.13.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    env:
      SONAR_VERSION: 4.2.0.1873
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Run unittests
        run: |
          set -o pipefail
          go test -cover -race -coverprofile=coverage.out -covermode=atomic -json ./... | tee test-report.out
      - name: Cache Sonar Scanner Client
        id: cache-sonar
        uses: actions/cache@v1
        with:
          path: sonar
          key: ${{ runner.os }}-sonar-${SONAR_VERSION}
      - name: Install Sonar Scanner Client
        if: steps.cache-sonar.outputs.cache-hit != 'true'
        run: |
          curl -L https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-${SONAR_VERSION}-linux.zip -o sonar.zip
          unzip sonar.zip
          mv sonar-scanner* sonar
          rm sonar.zip
      - name: Run sonarqube
        run: sonar/bin/sonar-scanner -X
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_LOGIN }}
